### ISSUE TITLE
typescript with async / await

### ISSUE THREAD

**Issue by Andersmholmgren** [elastic-coders/serverless-webpack#119]
Rather than using callbacks I prefer to use `async / await` but it seems the plugin is choking on it.

So rather than writing functions that look like

```
function handler(event: Request, context: any, callback: Callback): void {
```

I write functions that look like

```
function handler(event: Request): Promise<Response> {
```

and have an adapter that converts them to the callback form.

This works as long as I avoid `async/await` syntax which was a big part of my motivation. 

It seems to be blowing up in webpack / acorn. 

I've tried using https://www.npmjs.com/package/webpack-async-await plugin but still fails.

My config is 

```
var path = require('path');
var AsyncAwaitPlugin = require('webpack-async-await');

module.exports = {
  entry: './lib/handlers/hello.ts',
  target: 'node',
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' }
    ]
  },
  resolve: {
    extensions: ['.ts', '.js', '.tsx', '.jsx', '']
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: 'hello.js'
  },
  plugins: [
    new AsyncAwaitPlugin()
  ]  
};
```

my dependencies are

```
  "devDependencies": {
    "serverless-webpack": "^1.0.0-rc.4",
    "ts-loader": "^2.0.3",
    "tslint": "^5.0.0",
    "tslint-config-olo": "^0.1.0",
    "typescript": "^2.2.2",
    "typescript-formatter": "^5.1.3",
    "webpack": "^2.3.3",
    "webpack-async-await": "^1.1.0"
  }
```

The error I get is

```
ERROR in ./lib/handlers/hello.ts
Module parse failed: /Users/blah/typescript/serverlessThing/node_modules/ts-loader/index.js!/Users/blah/typescript/serverlessThing/lib/handlers/hello.ts Unexpected token (42:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (42:6)
    at Parser.pp$4.raise (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/webpack/lib/NormalModule.js:104:16)
    at NormalModule.onModuleBuild (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.loader (/Users/blah/typescript/serverlessThing/node_modules/ts-loader/dist/index.js:39:5)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/blah/typescript/serverlessThing/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/blah/typescript/serverlessThing/node_modules/serverless-webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/blah/typescript/serverlessThing/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)

  Error --------------------------------------------------

     Webpack compilation error, see above

```

**Comment by Andersmholmgren** [comment]
My bad. The problem was that I targeted es2017 with typescript. es2016 works
