### ISSUE TITLE
sls invoke local with webpack v3.0.0 throws "module not found"

### ISSUE THREAD

**Issue by QAnders** [elastic-coders/serverless-webpack#184]
# This is a (Bug Report / Feature Proposal)
Bug report

## Description
Installed v3.0.0 to try out `invoke local`. The previous version works fine on the same repo using `sls webpack...`
I can see that SLS builds with webpack but then throws the error about missing module (see stack trace).

## Additional Data

* ***Serverless-Webpack Version you're using***: 3.0.0
* ***Webpack version you're using***: 3.5.0
* ***Serverless Framework Version you're using***: 1.19.0
* ***Operating System***: Windows 10
* ***Stack Trace (if available)***:
```
{ Error: Cannot find module './.webpack/service/handler'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at AwsInvokeLocal.invokeLocalNodeJs (./npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:156:33)
    at AwsInvokeLocal.invokeLocal (./npm/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:114:19)
    at AwsInvokeLocal.tryCatcher (./npm/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./npm/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (./npm/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (./npm/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (./npm/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (./npm/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (./npm/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (./npm/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5) code: 'MODULE_NOT_FOUND' }
```

**Comment by HyperBrain** [comment]
Can you post your function definition from `serverless.yml` and your `webpack.conf.js`? Maybe it's something that has to be changed there, because the new sls-webpack version tries to lookup the function handlers.

**Comment by QAnders** [comment]
```
service: qip-lambda-invoice-routing

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs6.10
[snip]
  receiveInvoice:
    handler: handler.receiveInvoiceHandler

```

```
module.exports = {
  entry: './handler.js',
  target: 'node',
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: ['babel-loader'],
        include: __dirname,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  externals: [
    {
      pg: true
    }
  ],
  node: {
    fs: 'empty'
  }
};

```

**Comment by HyperBrain** [comment]
Can you try to use automatic entry resolution, so that the plugin tries to determine the handler? Please change the webpack.conf.js as follows:
```
const slsw = require('serverless-webpack');
module.exports = {
  ...
  entry: slsw.lib.entries,
  ...
};
```
Additionally you should use Webpack 2.x.x or Webpack 3.x.x (as a dev dependency of your project). You have to use `module.rules` instead of `modules.loaders` for the newer webpack versions (the sample below also uses babel-preset-node6). Webpack 1.x.x might not work very well.
```
...
	module: {
		rules: [
			{
				// Process ES6 with Babel.
				test: /\.js$/,
				use: [
					{
						loader: "babel-loader",
						options: {
							presets: [ "node6" ],
							plugins: []
						}
					}
				],
			}
		]
	}
...
```

**Comment by HyperBrain** [comment]
PS: You can check the samples at [v3.0.0/examples](https://github.com/elastic-coders/serverless-webpack/tree/v3.0.0/examples)

**Comment by QAnders** [comment]
Thanks! Changing the `entry` works fine!

**Comment by bouiboui** [comment]
I had this error too, and it was due to having a dot in my handler's filename (ex: `my.handler.js`). In the serverless.yml file, the handler line looked like:
```yaml
handler: src/handlers/my.handler.doStuff
```
I guess that confused serverless-webpack.
Not saying it's an issue, but it might help since this page is the first thing that pops up on Google.
