### ISSUE TITLE
Unable to deploy functions individually

### ISSUE THREAD

**Issue by simoami** [elastic-coders/serverless-webpack#63]
While service deployment works great, I'm unable to deploy functions individually:

```
$ serverless deploy function -f getAllUsers -s dev
Serverless: Deploying function: getAllUsers...
Serverless: Packaging function: getAllUsers...
fs.js:987
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/projects/service-users/node_modules/.bin/babel'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at files.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:55:26)
    at Array.forEach (native)
    at WriteStream.output.on (/usr/local/lib/node_modules/serverless/lib/plugins/package/lib/zipService.js:49:13)
    at emitOne (events.js:96:13)
    at WriteStream.emit (events.js:188:7)
    at WriteStream.<anonymous> (fs.js:2094:10)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Is it even supported?

**Comment by bassbump** [comment]
Doesn't look like this is supported

**Comment by thenikso** [comment]
we will be tracking this in #60 please report there!
