### ISSUE TITLE
Help: examples/babel ,  Error("Cannot find module \"../package.json\"")

### ISSUE THREAD

**Issue by ansonla3** [elastic-coders/serverless-webpack#68]
Just clone the project & tried, then npm install request package, and using es6 import syntax

import request from "request";

I got this error
	var VERSION = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../package.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).version;
	                                                                                                                                                                
Error: Cannot find module "../package.json"

Any configs need to be set ? Please advise. thanks

**Comment by thenikso** [comment]
to clarify:

1. you are in the examples/babel directory
2. without any changes you can run the example fine (npm i && sls webpack serve)
3. you add that import to the example handler.js
4. at this point you get that error?

**Comment by jamesandersen** [comment]
I'm getting something very similar here.   I've tried using two different npm packages (`axios` and `node-fetch`).   Both of them, when used in the lambda function and then starting `sls webpack serve` resulting in a stacktrace.

```
/app/.webpack/handler.js:386
	var convert = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"encoding\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).convert;
	                                                                                                                                                         ^
Error: Cannot find module "encoding"
    at webpackMissingModule (/app/.webpack/handler.js:386:80)
    at Object.module.exports (/app/.webpack/handler.js:386:165)
    at __webpack_require__ (/app/.webpack/handler.js:20:30)
    at Object.<anonymous> (/app/.webpack/handler.js:86:13)
    at __webpack_require__ (/app/.webpack/handler.js:20:30)
    at Object.<anonymous> (/app/.webpack/handler.js:49:21)
    at __webpack_require__ (/app/.webpack/handler.js:20:30)
    at Object.defineProperty.value (/app/.webpack/handler.js:40:18)
    at Object.<anonymous> (/app/.webpack/handler.js:43:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at ServerlessWebpack.loadHandler (app/node_modules/serverless-webpack/lib/run.js:21:20)
    at Watching.handler (/app/node_modules/serverless-webpack/lib/serve.js:24:39)
    at Watching._done (/app/node_modules/serverless-webpack/node_modules/webpack/lib/Compiler.js:81:7)
    at Watching.<anonymous> (/app/node_modules/serverless-webpack/node_modules/webpack/lib/Compiler.js:61:18)
    at Compiler.emitRecords (/app/node_modules/serverless-webpack/node_modules/webpack/lib/Compiler.js:282:37)
    at Watching.<anonymous> (/app/node_modules/serverless-webpack/node_modules/webpack/lib/Compiler.js:58:19)
    at /app/node_modules/serverless-webpack/node_modules/webpack/lib/Compiler.js:275:11
 ```

After starting `sls webpack serve` with the debugger and then tracing back from where this error is thrown, the problem seems to be that webpack isn't resolving some of the child dependencies of these packages.  The above stack trace occurs when using `node-fetch`; the only difference when using `axios` was that it complained about not finding `debug` instead of `encoding`.  
* `axios` => `debug`
* `node-fetch` => `encoding`

Any clues/insights would be much appreciated...

**Comment by jamesandersen** [comment]
Update:  I tried simply running `webpack --progress --color --watch --display-error-details` and found the following warning:
```
WARNING in ./~/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/app/node_modules/webpack/lib/dependencies/Co
mmonJsRequireContextDependency.js:27:4)
    at Compilation.reportDependencyErrorsAndWarnings (/app/node_modules/webpack/lib/Compilation.js
:663:24)
    at Compilation.finish (/app/node_modules/webpack/lib/Compilation.js:526:9)
    at /app/node_modules/webpack/lib/Compiler.js:472:16
    at /app/node_modules/webpack/node_modules/tapable/lib/Tapable.js:225:11
    at /app/node_modules/webpack/lib/Compilation.js:472:11
    at /app/node_modules/webpack/lib/Compilation.js:443:13
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

That led me to [this `webpack` thread](https://github.com/webpack/webpack/issues/196) about problems with webpack resolving require statements where the module to be required is an expression.

Still not entirely sure how to resolve this... but will post back if I get it figured out.

**Comment by jamesandersen** [comment]
OK...   the [Configure Section](https://github.com/elastic-coders/serverless-webpack#configure) of the docs turned out to have the resolution to my issues.  

I've used webpack for several browser based applications but this was the first time using it to package a node application so these module resolution issues weren't clearly related to the need to externalize the modules.  Sigh...

**Comment by HyperBrain** [comment]
@jamesandersen Is there anything still open with this issue, or can I close it?

BTW: The project is up and running again - if you abandoned the use (as it was unmaintained for some time) you could give the latest version a try.

**Comment by jamesandersen** [comment]
Thanks @HyperBrain, nothing further needed for me on this issue.    I'll have to grab latest soon.

**Comment by HyperBrain** [comment]
Then I'll close this. If anything new raises with the latest and upcoming versions, we can open new issues.
