### ISSUE TITLE
Debugging serverless with webpack ...

### ISSUE THREAD

**Issue by cdichiara** [elastic-coders/serverless-webpack#94]
Hi,

Just a quick question for the experts ... I've switched over to using webpack for both loader use and to eliminate some development node modules from being loaded into the serverless Lambda function. Getting a pretty cryptic error out of the Lambda right now:

```
Syntax error in module 'handleClientApi': SyntaxError
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```
Anyone else run into this problem? Any good way to go about debugging it? I'm guessing it's happening in the webpack bootstrap or around there ... `sls webpack serve` actually serves a functional server ... at least until the property in the first parameter to the handler, `event.body`, isn't a string like it is on the actual Lambda - it's an object, and my code barfs on it.

Regardless, this Syntax Error has gotten me stumped because I don't have a good way to debug it. Has anyone else run into this?

serverless@1.5.0
serverless-webpack@1.0.0-rc.4

**Comment by cdichiara** [comment]
Ah, it's not webpack ... it's that AWS Lambda is still running Node v.4.3.2 & I must be using an ES2016 feature that isn't supported yet ... joyful.
